name: kronerulling-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.4
  - pip 22.2.2
  - setuptools>=65.3.0
  - wheel>=0.37.1
  - pip:
      - matplotlib == 3.6.2
      - jupyterlab